name: shellcheck

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: "macos-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Shellcheck
        run: brew install shfmt shellcheck
      - name: Lint
        run: |
          shfmt -d .
          shellcheck -s sh *.sh
